### ISSUE TITLE
P35X V5 Register Decoding

### ISSUE THREAD

**Issue by marius96s** [jertel/p37-ec#1]
Hello,
this isn't a P37 related issue, but I own a P35X v5 and I updated my EC firmware and afterwards my HDMI port isn't recognized anymore! not even the BIOS settings or the Post Screen is getting through my HDMI port, neither do my Laptop recognize when I insert an HDMI cable. 
my question is, where do you get the information about what register controls which function of the P37 of yours ?
I tried controlling some functions with the Control center and check which register changes, but I also cant access the Monitor Settings.
I tried and most of the BITs you wrote down do match with the BITs on my Laptop. 
But is there a BIT which controls the HDMI port given through, or might this even be some other issue ?
is it safe to just try enabling bit for bit, until I reach to the one controlling the HDMI Port, even if it's a very very tideous task to do ? I Cant find anything on the internet about this, no one is having this excat issue.

Thanks!

**Comment by jertel** [comment]
Sorry to hear about your P37 HDMI issues. 

The register data was found via trial and error. There is no published data on these machines that I could find. I don't know if such an HDMI enable bit exists. 

Sending values to random bits could lead to problems or bricking your machine. I have not seen that behavior personally, I'm only speaking from a cautionary mindset, since you could accidentally be telling the system to shut off all cooling fans, or changing voltages, etc. I just don't know enough about what else is controlled via that EC, unfortunately.

**Comment by marius96s** [comment]
yeah, I thought of changing random values could lead to something not good.
Gigabyte Support isn‘t a great help.
Thank you for your fast response anyway :)
